name: nexus_hub_app
description: Nexus Hub Flutter frontend
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  signals_flutter: ^6.1.4
  go_router: ^14.8.1
  dio: ^5.8.0+1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  path: ^1.9.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  shimmer: ^3.0.0
  equatable: ^2.0.7
  url_launcher: ^6.3.1
  fl_chart: ^0.70.2
  flutter_reorderable_grid_view: ^5.7.0
  super_clipboard: ^0.9.1
  flutter_quill: ^11.0.0
  diff_match_patch: ^0.4.1
  easy_mail: ^0.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
