name: nexus_hub_api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  dart_frog: ^1.1.0
  dio: ^5.8.0+1
  shelf_cors_headers: ^0.1.2
  sqlite3: ^2.4.0

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.0
  test: ^1.0.0
